/*
 * File: app/view/log/Detail.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CACS.view.logging.Details', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.loggingdetails',

    requires: [
        'CACS.view.logging.DetailsViewModel',
        'Ext.form.field.Display',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'loggingdetails'
    },
    height: '',
    margin: 10,
    modelValidation: false,
    width: 800,
    title: '事件明细',

    items: [
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'ID:',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: '事件名称',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: '来源',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: '事件类型',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: '操作用户',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: 'IP地址',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            anchor: '100%',
            fieldLabel: '事件时间',
            value: 'Display Field'
        },
        {
            xtype: 'textareafield',
            anchor: '100%',
            height: 62,
            width: 778,
            fieldLabel: '内容'
        }
    ]

});