/*
 * File: app/view/log/List.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CACS.view.logging.List', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.logginglist',

    requires: [
        'CACS.view.logging.ListViewModel',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.grid.column.Column',
        'Ext.grid.column.Date',
        'Ext.toolbar.Fill',
        'Ext.toolbar.Paging',
        'Ext.view.Table'
    ],

    viewModel: {
        type: 'logginglist'
    },
    height: 297,
    title: '日志查看器',
    store: 'logging.LogStore',

    viewConfig: {
        width: ''
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            width: '',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: '搜索',
                    labelWidth: 30
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    iconCls: 'zoom',
                    text: '详细搜索'
                }
            ]
        },
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: '',
            displayInfo: true,
            store: 'logging.LogStore'
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'Id',
            text: 'Id'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EventName',
            text: '事件名称'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Source',
            text: '来源'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EventType',
            text: '事件类型'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'OperateUser',
            text: '操作用户'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Ip',
            text: 'IP地址'
        },
        {
            xtype: 'datecolumn',
            dataIndex: 'EventTime',
            text: '事件时间'
        }
    ]

});